
language: bash
sudo: true
install:
  - sudo apt-get update -qq
  - git clone -b v2015.1.2 https://github.com/Freifunk-Troisdorf/gluon /home/travis/build/Freifunk-Troisdorf/gluon 
  - git clone -b v2015.1 https://github.com/Freifunk-Troisdorf/site /home/travis/build/Freifunk-Troisdorf/gluon/site
script: 
 - wget https://raw.githubusercontent.com/Freifunk-Troisdorf/build-fw/master/site_check.sh && chmod +x site_check.sh
 - site_check.sh
